/**
 * Build script: bundles the React SPA into build/.
 * Data is loaded at runtime from the D1 API — no generated data files.
 *
 * Usage: bun ./src/build.ts
 */

export {};

const srcDir = import.meta.dir;
const buildDir = `${srcDir}/../build`;

const { rmSync, mkdirSync } = await import('fs');
rmSync(buildDir, { recursive: true, force: true });
mkdirSync(buildDir, { recursive: true });

// Build worker (optimizer Web Worker) first so we can inline its code
const workerResult = await Bun.build({
  entrypoints: [`${srcDir}/optimizer.worker.ts`],
  outdir: buildDir,
  naming: 'optimizer.worker.js',
});
if (!workerResult.success) {
  console.error('✗ Worker build failed:');
  for (const log of workerResult.logs) console.error(log);
  process.exit(1);
}

const workerCode = await Bun.file(`${buildDir}/optimizer.worker.js`).text();
await Bun.write(
  `${srcDir}/optimizer-worker-code.generated.ts`,
  `// AUTO-GENERATED by build.ts — do not edit\nexport const WORKER_CODE = ${JSON.stringify(workerCode)};\n`
);
console.log('✓ Generated optimizer worker inline code');

// Build main app
const result = await Bun.build({
  entrypoints: [`${srcDir}/index.html`],
  outdir: buildDir,
});

if (!result.success) {
  console.error('✗ Build failed:');
  for (const log of result.logs) console.error(log);
  process.exit(1);
}

// Clean up standalone worker file (now inlined)
try {
  await Bun.file(`${buildDir}/optimizer.worker.js`).delete();
} catch {}

console.log(`✓ Bundled ${result.outputs.length} files to build/`);
