/**
 * Build script: rebuilds DB from CSVs, extracts all data needed by the client,
 * writes src/data.generated.ts, then bundles the app.
 *
 * Usage: bun ./src/build.ts
 */
import { Database } from 'bun:sqlite';
import Papa from 'papaparse';

const srcDir = import.meta.dir;

// ── Step 1: Rebuild database ─────────────────────────────────────────────

const dbPath = `${srcDir}/database.db`;
const dbFile = Bun.file(dbPath);
if (await dbFile.exists()) await dbFile.delete();

const db = new Database(dbPath);
const sql = await Bun.file(`${srcDir}/create_database.sql`).text();
db.transaction(() => db.run(sql))();

const csvTables = [
  'class_dances',
  'classes',
  'dancer_classes',
  'dancers',
  'dances',
  'recitals',
  'recital_groups',
];

for (const table of csvTables) {
  const data = Papa.parse(await Bun.file(`${srcDir}/${table}.csv`).text(), {
    header: true,
    dynamicTyping: true,
    skipEmptyLines: true,
  });
  db.transaction(() => {
    const columns = data.meta.fields!;
    const placeholders = columns.map(() => '?').join(', ');
    const stmt = db.prepare(
      `INSERT INTO ${table} (${columns.join(', ')}) VALUES (${placeholders})`
    );
    for (const row of data.data as Record<string, any>[]) {
      stmt.run(...columns.map(col => row[col]));
    }
  })();
}

// ── Step 2: Extract data ─────────────────────────────────────────────────

const dances = db
  .query('SELECT dance_id, dance_style, dance_name, choreography, song, artist FROM dances')
  .all();

const groups = db
  .query('SELECT recital_group, show_order FROM recital_groups')
  .all()
  .map((g: any) => ({ ...g, show_order: JSON.parse(g.show_order) }));

const comboPairs = db
  .query(
    `SELECT a.dance_id AS dance_id_1, b.dance_id AS dance_id_2
       FROM class_dances a
       JOIN class_dances b ON a.class_id = b.class_id AND a.dance_id < b.dance_id
       JOIN classes c ON a.class_id = c.class_id
      WHERE c.class_name LIKE '%Combo%'`
  )
  .all();

const dancerRows = db
  .query(
    `SELECT DISTINCT d.dance_id, dc.dancer_name
       FROM dances d
       INNER JOIN class_dances cd ON d.dance_id = cd.dance_id
       INNER JOIN dancer_classes dc ON cd.class_id = dc.class_id`
  )
  .all() as { dance_id: number; dancer_name: string }[];

const dancersByDance: Record<number, string[]> = {};
for (const r of dancerRows) {
  (dancersByDance[r.dance_id] ??= []).push(r.dancer_name);
}

db.close();

// ── Step 3: Write generated data module ──────────────────────────────────

const output = `// AUTO-GENERATED by build.ts — do not edit
import type { DanceRow, RecitalGroupRow, ComboPair } from './types';

export const DANCES: DanceRow[] = ${JSON.stringify(dances)};

export const GROUPS: RecitalGroupRow[] = ${JSON.stringify(groups)};

export const COMBO_PAIRS_DATA: ComboPair[] = ${JSON.stringify(comboPairs)};

export const DANCERS_BY_DANCE: Record<number, string[]> = ${JSON.stringify(dancersByDance)};
`;

await Bun.write(`${srcDir}/data.generated.ts`, output);
console.log('✓ Generated src/data.generated.ts');

// ── Step 4: Clean build folder & bundle ──────────────────────────────────

const buildDir = `${srcDir}/../build`;
const { rmSync, mkdirSync } = await import('fs');
rmSync(buildDir, { recursive: true, force: true });
mkdirSync(buildDir, { recursive: true });

// Build worker first so we can inline its code into the main bundle
const workerResult = await Bun.build({
  entrypoints: [`${srcDir}/optimizer.worker.ts`],
  outdir: buildDir,
  naming: 'optimizer.worker.js',
});
if (!workerResult.success) {
  console.error('✗ Worker build failed:');
  for (const log of workerResult.logs) console.error(log);
  process.exit(1);
}

const workerCode = await Bun.file(`${buildDir}/optimizer.worker.js`).text();
await Bun.write(
  `${srcDir}/optimizer-worker-code.generated.ts`,
  `// AUTO-GENERATED by build.ts — do not edit\nexport const WORKER_CODE = ${JSON.stringify(workerCode)};\n`
);
console.log('✓ Generated optimizer worker inline code');

// Build main app (imports the worker code module)
const result = await Bun.build({
  entrypoints: [`${srcDir}/index.html`],
  outdir: buildDir,
});

if (!result.success) {
  console.error('✗ Build failed:');
  for (const log of result.logs) console.error(log);
  process.exit(1);
}

// Clean up the standalone worker file (now inlined in main bundle)
const { unlinkSync } = await import('fs');
try { unlinkSync(`${buildDir}/optimizer.worker.js`); } catch {}

console.log(`✓ Bundled ${result.outputs.length} files to build/`);
